### ISSUE TITLE
Convert HTML to kramdown Markdown

### ISSUE THREAD

**Issue by andreamussap** [andreamussap/Axway_Docs4All_Hackathon#3]
# Description

We need a set of docs in markdown format for the hackathon project, so we can edit these docs in Netlifly CMS and on GitHub.

Convert '[API Gateway 7.7 Apache Cassandra Administrator Guide](https://docs.axway.com/bundle/APIGateway_77_CassandraGuide_allOS_en_HTML5/page/Content/CassandraTopics/CassandraStartPage.htm)' to markdown

## Tasks

- [ ] Investigate/confirm that the markdown flavor must be **kramdown** to work with **Jekyll**.
- [ ] Export Cassandra guide from Flare
- [ ] Convert the files to markdown
- [ ] Import files to this github repo

**Comment by andreamussap** [comment]
## Task 1. Verify 

Done.

If you’re using a static site generator, [see the specific Markdown syntax used](https://idratherbewriting.com/learnapidoc/pubapis_markdown.html#development-by-popular-demand-versus-by-committee). With **Jekyll**, the default Markdown is **kramdown**. kramdown gives you more capabilities than the basic Markdown...

I didn't find a way to convert HTML directly to kramdown, so will convert it to GitHub-flavored Markdown instead.
> "[kramdown is largely compatible with GitHub-flavored Markdown](https://idratherbewriting.com/learnapidoc/pubapis_markdown.html#development-by-popular-demand-versus-by-committee)"

## Task 2. Export Cassandra Admin guide from Flare

Done.
